name: Setup new repo created from Template

on:
  release:
    types: [published]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    if: github.event.release.name == 'SETUP_NEW_PROJECT'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Packages Structure
        run: |
          new_package=${{ fromJSON(github.event.release.body).groupId }}
          echo "new_package: $new_package"
          package_folder=${new_package//.//}
          echo "package_folder: $package_folder"
          base_folder="$(pwd)/src/main/java"
          echo "yendo a base_folder: $base_folder"
          cd $base_folder
          echo "crear temporary"
          mkdir -p temporary
          echo "source_path: $base_folder/com/modyo/example/"
          source_path="$base_folder/com/modyo/example/"
          echo "temp_path: $base_folder/temporary/"
          temp_path="$base_folder/temporary/"
          echo "destination_path: $base_folder/$package_folder"
          destination_path="$base_folder/$package_folder"
          echo "mover $source_path* $temp_path"
          mv $source_path* $temp_path
          echo "eliminar package original $base_folder/com"
          rm -r "$base_folder/com"
          echo "crear $package_folder"
          mkdir -p $package_folder
          echo "mover $temp_path* $destination_path"
          mv $temp_path* $destination_path
          echo "eliminar temp_path: $temp_path"
          rm -r $temp_path
          cd $destination_path
          pwd
          ls -a

      - name: Replace Project Name in Files
        run: |
          project_name=${GITHUB_REPOSITORY#*/}
          echo "project_name: $project_name
#          echo "replace command: 's/templatems/$project_name/g'"
          find . -type f -not -path "./.github/workflows/*" -print0 | xargs -0 sed -i '' -e "s/templatems/$project_name/g"
          find . -type f -print | xargs grep $project_name

      - name: Check Git Status
        run: git status

#      - name: Commit and Push Changes
#        uses: devops-infra/action-commit-push@master
#        with:
#          github_token: "${{ secrets.GITHUB_TOKEN }}"
#          add_timestamp: false
#          commit_prefix: "[AUTO] "
#          commit_message: "Automatic commit"
#          force: false
#      - name: Commit & Push changes
#        uses: actions-js/push@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
