name: Setup new repo created from Template

on: [push]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set new project name in files
        run: |
          find . -type f -print0 | xargs -0 sed -i 's/templatems/nuevonombre/g'
          echo "-----------------------------------------"
          find . -type f -print | xargs grep "nuevonombre"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
