name: Setup new repo created from Template

on:
  release:
    types: [published]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set new project name in files
        run: |
          git status
          project_name=${GITHUB_REPOSITORY#*/}
          echo "project_name: $project_name"
          find . -type f -not -path './.github/workflows/*' -print0 | xargs -0 sed -i 's/$project_name/templatems/g'
          echo "-----------------------------------------"
          find . -type f -print | xargs grep $project_name
      - name: Commit and Push Changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Automatic commit"
          force: false

#          target_branch: update/version
#      - name: Commit & Push changes
#        uses: actions-js/push@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
