name: Setup new repo created from Template

on:
  release:
    types: [published, edited]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    if: github.event.release.name == 'SETUP_NEW_PROJECT'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set new project name in files
        run: |
          git status
          project_name=${GITHUB_REPOSITORY#*/}
          echo "project_name: $project_name"
          echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"
          base_package=${{ fromJSON(github.event.release.body).groupId }}
          echo "base_package: $base_package"
          IFS='.' read -ra package_folders <<< $base_package
          echo "package_folders: $package_folders"
          for i in "{$package_folders[@]}"; do printf "$i "; done

#          find . -type f -not -path './.github/workflows/*' -print0 | xargs -0 sed -i 's/$project_name/templatems/g'
#          echo "-----------------------------------------"
#          find . -type f -print | xargs grep $project_name
#      - name: Commit and Push Changes
#        uses: devops-infra/action-commit-push@master
#        with:
#          github_token: "${{ secrets.GITHUB_TOKEN }}"
#          add_timestamp: false
#          commit_prefix: "[AUTO]"
#          commit_message: "Automatic commit"
#          force: false

#          target_branch: update/version
#      - name: Commit & Push changes
#        uses: actions-js/push@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
