name: Setup new repo created from Template

on: [push]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Search by Files Content
        run: |
          pwd
          ls -a
          echo "-----------------------------------------"
          find . -type f -print | xargs grep "templatems"
          echo "-----------------------------------------"
          find . -type f -print0 | xargs -0 sed -i 's/templatems/nuevonombre/g'
          echo "-----------------------------------------"
          find . -type f -print | xargs grep "nuevonombre"
      #  setup-files-content:
