name: Setup new repo created from Template

on: [push]

jobs:
  setup-project-by-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Search by Files Content
        run: |
          pwd
          ls -a
          find . -type f -print | xargs grep "templatems"
      #  setup-files-content:
